name: Generate Snake Animation
on:
  schedule:
    - cron: "0 3 * * *"  # Runs at 03:00 UTC daily
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use the latest version

      - name: Generate Snake Animation
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist  # Store output in the 'dist' folder

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
