name: Generate Snake Animation
on:
  schedule:
    - cron: "0 3 * * *"  # Runs at 03:00 UTC daily
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures repo is accessible

      - name: Generate Snake Animation
        run: |
          mkdir -p dist
          curl -o dist/github-contribution-grid-snake.svg "https://ghchart.rshah.org/eltonbaidoo"

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main || true
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          git add output/github-contribution-grid-snake.svg
          git commit -m "Updated Snake Animation"
          git push
